version: '3.9'

services:
  db:
    image: postgres:15
    container_name: document_processing_db
    restart: always
    environment:
      POSTGRES_DB: document_processing
      POSTGRES_USER: tojidev
      POSTGRES_PASSWORD: toaidev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: document_processing_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
